version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r single_service/requirements.txt

  build:
    commands:
      - echo "Running tests..."
      - pytest single_service/tests
