version: 0.2

phases:
  install:
    commands:
      - pip install -r single_service/requirements.txt

  build:
    commands:
      - echo "Running tests..."
      - export PYTHONPATH=$CODEBUILD_SRC_DIR
      - pytest single_service/tests
